const path = require('path');
const fs = require('fs');
const express = require('express');
const session = require('express-session');
const SQLiteStore = require('connect-sqlite3')(session);
const rateLimit = require('express-rate-limit');
const helmet = require("helmet");

// Load Environment Configuration First
const env = require('./config/env');

// Import DB Instance
const db = require('./config/db');

// Create Express App
const app = express();
app.set('trust proxy', 1);

// Ensure log directory exists
const logDir = path.join(__dirname, '../log');
if (!fs.existsSync(logDir)) {
    fs.mkdirSync(logDir, { recursive: true });
}

// Resolve portal public address from env (strictly PUBLIC_DNS, using https)
const publicDns = process.env.PUBLIC_DNS || '127.0.0.1';
const portalUrl = `https://${publicDns}`;
const portalBaseUrl = `${portalUrl}${env.BASE_PATH || '/homepage'}`;
const parsedPortalUrl = new URL(portalUrl);

// Auto-generate ChromeExtension/config.js based on resolved configuration
try {
  const allowedOrigins = [
    parsedPortalUrl.origin,
    "https://localhost",
    "https://127.0.0.1",
    "http://localhost:8080",
    "http://127.0.0.1:8080"
  ];

  if (!allowedOrigins.includes(parsedPortalUrl.origin)) {
    allowedOrigins.push(parsedPortalUrl.origin);
  }

  const extensionConfigPath = path.join(__dirname, '../../ChromeExtension/config.js');
  const configContent = `// Automatically generated by INHACK Portal Server. Do not edit.
const PORTAL_URL = "${portalBaseUrl}";
const ALLOWED_ORIGINS = ${JSON.stringify(allowedOrigins)};
`;
  fs.writeFileSync(extensionConfigPath, configContent, 'utf8');

  // Auto-package ChromeExtension zip file
  const { exec } = require('child_process');
  exec('zip -r ../INHACK-Homepage/src/INHACK-Extension.zip background.js button.css content.js images interceptor.js manifest.json popup.css popup.html popup.js config.js', { cwd: path.join(__dirname, '../../ChromeExtension') }, (err) => {
    if (err) {
      console.error('[Extension Packager] Failed to auto-package extension:', err.message);
    } else {
      console.log('[Extension Packager] Extension successfully packaged with current configuration.');
    }
  });
} catch (e) {
  console.error('[Extension Config Gen Error] Failed to generate extension config:', e.message);
}

// Set up dynamic connect origins for CSP
const connectOrigins = ["'self'", "https://dreamhack.io"];
connectOrigins.push(parsedPortalUrl.origin);
if (parsedPortalUrl.hostname === 'localhost' || parsedPortalUrl.hostname === '127.0.0.1') {
  const otherLocal = parsedPortalUrl.hostname === 'localhost' ? '127.0.0.1' : 'localhost';
  connectOrigins.push(`https://${otherLocal}`);
}
connectOrigins.push("http://localhost:8080", "http://127.0.0.1:8080", "https://localhost", "https://127.0.0.1");

// Security headers with Helmet
app.use(helmet({
  crossOriginEmbedderPolicy: false,
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      styleSrc: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
      fontSrc: ["'self'", "https://fonts.gstatic.com"],
      imgSrc: ["'self'", "data:", "http:", "https:"],
      scriptSrc: ["'self'", "'unsafe-inline'"],
      connectSrc: connectOrigins
    }
  }
}));

// Request Body Parsers
app.use(express.urlencoded({ limit: '10mb', extended: true }));
app.use(express.json({ limit: '10mb' }));

// Session Middleware
const sessionStore = new SQLiteStore({
  db: 'sessions.sqlite',
  dir: path.join(__dirname, '..')
});
sessionStore.on('error', (err) => {
  console.error('[Session Store Error] Failed to interact with SQLite session database:', err.message);
});

app.use(session({
    name: env.SESSION_NAME,
    store: sessionStore,
    secret: env.SESSION_SECRET || 'default',
    resave: false,
    saveUninitialized: false,
    cookie: {
      maxAge: 24 * 60 * 60 * 1000,
      sameSite: 'lax',
      secure: false,
      httpOnly: true,
      path: env.BASE_PATH || '/homepage'
    },
    rolling: true,
}));

// Import Routers
const authRouter = require('./routes/auth');
const adminRouter = require('./routes/admin');
const dreamhackRouter = require('./routes/dreamhack');
const pagesRouter = require('./routes/pages');

// Create Homepage Router
const homepageRouter = express.Router();

// Password Change Enforcer Middleware
const { passwordEnforceMiddleware } = require('./middlewares/auth');
homepageRouter.use(passwordEnforceMiddleware);

// Rate Limiting
homepageRouter.use(rateLimit({
  windowMs: 10 * 60 * 1000,
  max: 500,
  message: '너무 많은 요청을 보냈습니다. 10분 후에 다시 시도해주세요.',
  standardHeaders: true,
  legacyHeaders: false,
}));

// API Routers
homepageRouter.use('/', authRouter);
homepageRouter.use('/admin', adminRouter);
homepageRouter.use('/dreamhack', dreamhackRouter);

// Pages & Fragment Router (Requires higher priority than static /frags)
homepageRouter.use('/', pagesRouter);

// Static Directories
homepageRouter.use('/frags', express.static(path.join(__dirname, '../src/html/fragments')));
homepageRouter.use('/assets', express.static(path.join(__dirname, '../src')));
homepageRouter.use('/images', express.static(path.join(__dirname, '../images')));

// Mount Homepage Router to basePath
app.use(env.BASE_PATH || '/homepage', homepageRouter);

// Redirect / to basePath for convenience
app.get('/', (req, res) => {
  res.redirect(env.BASE_PATH || '/homepage');
});

// Server Listen
const PORT = env.PORT;
app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server is running on http://localhost:${PORT}`);
});