// Automatically generated by INHACK Portal Server. Do not edit.
const PORTAL_URL = "https://127.0.0.1/homepage";
const ALLOWED_ORIGINS = ["https://127.0.0.1","https://localhost","https://127.0.0.1","http://localhost:8080","http://127.0.0.1:8080"];
